POST http://localhost:3030/register 
Content-Type: application/json

{
  "username": "Tyleriscool",
  "password": "Password123"
}

###

POST http://localhost:3030/signin 
Content-Type: application/json

{
  "username": "Tyleriscool",
  "password": "Password123"
}

###

GET http://localhost:3030/getUserList
Content-Type: application/json

###

POST http://localhost:3030/addToJunction
Content-Type: application/json

{
  "mal_id": 226,
  "userId": 1
}
